apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: key-producer-ingress
  namespace: rabbitmq-demo
spec:
  ingressClassName: nginx
  rules:
  - host: rabbitmq-demo.javajon.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: key-producer
            port:
              number: 80
